# Generated by Django 5.2.13 on 2026-05-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cvs/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('other', 'Other')], default='pdf', max_length=10)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('cleaned_text', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('summary_section', models.TextField(blank=True, default='')),
                ('skills_section', models.TextField(blank=True, default='')),
                ('experience_section', models.TextField(blank=True, default='')),
                ('education_section', models.TextField(blank=True, default='')),
                ('languages_section', models.TextField(blank=True, default='')),
                ('projects_section', models.TextField(blank=True, default='')),
                ('certifications_section', models.TextField(blank=True, default='')),
                ('interests_section', models.TextField(blank=True, default='')),
                ('detected_skills', models.TextField(blank=True, default='', help_text='Comma-separated list of detected technical skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='nlp_engine.cvdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_features', models.JSONField(default=list)),
                ('preprocessed_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_vector', to='nlp_engine.cvprofile')),
            ],
        ),
    ]
